# Generated by Django 5.0.3 on 2026-04-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Менеджер: доступ к AI-дашборду и системе промокодов'),
        ),
    ]
