# Generated by Django 5.0.3 on 2026-04-07 15:29

import django.db.models.deletion
import promo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studio', '0003_hall_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=promo.models.generate_promo_code, max_length=32, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=30, help_text='Скидка в процентах (1-100)')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('hour_from', models.IntegerField(default=9, help_text='Начало действия скидки (час, 0-23)')),
                ('hour_to', models.IntegerField(default=21, help_text='Конец действия скидки (час, 0-23)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promos', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='studio.hall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
