# Generated by Django 5.0.3 on 2026-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promocode_expiry_promocode_promo_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='promo_type',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='usage_count',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='value',
        ),
    ]
