# Generated by Django 5.0.3 on 2026-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='halls/'),
        ),
    ]
