# Generated by Django 5.0.3 on 2026-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_hall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
