# Generated by Django 5.0.3 on 2026-04-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_hall_description_hall_is_active_order_applied_promo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='is_active',
        ),
    ]
