# Generated by Django 5.0.3 on 2026-04-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_protect_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='studio.hall'),
        ),
    ]
