# Generated by Django 5.0.3 on 2026-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает'), ('CONFIRMED', 'Подтверждено'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=20),
        ),
    ]
